---
packages:
  - ack
  - autoconf
  - automake
  - azure-cli
  - build-essential
  - cmake
  - curl
  - dotnet-sdk-6.0
  - dotnet-sdk-7.0
  - dotnet-sdk-8.0
  - g++
  - gettext
  - libsqlite3-dev
  - libtool
  - libtool-bin
  - libreadline-dev
  - luarocks
  - mutt
  - ninja-build
  - python3-pip
  - pkg-config
  - ripgrep
  - golang-go
  - silversearcher-ag
  - sqlite3
  - tmux
  - tmuxinator
  - unzip
  - zsh

casks:
  - automake
  - azure-cli
  - claude-code
  - cmake
  - curl
  - dotnet-sdk
  - fabric
  - gettext
  - gh
  - libtool
  - mutt
  - ninja
  - oven-sh/bun/bun
  - pkg-config
  - npm
  - ripgrep
  - rustup
  - stylua
  - sqlite3
  - tealdeer
  - tree-sitter
  - luarocks
  - tmux
  - tmuxinator
  - shellcheck
  - swiftbar
  - yt-dlp
  - warp

debs:
  - https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
  - https://github.com/cli/cli/releases/download/v2.52.0/gh_2.52.0_linux_amd64.deb

pips:
  - pynvim
  - qmk
  - ansible-lint[yamllint]
  - openai

npms:
  - "@anthropic-ai/claude-code"
